### PR TITLE
Units are now paused in post-game screen

### PR DESCRIPTION
**Pull request by Microhive**
- Post game all units are paused and turned invulnerable. 
- In order to ensure that no units are trained - in case the game is reset - the ownership of all buildings are also temporarily changed to another player and back to the original owner. This resets the training queue. 
- Invulnerability is necessary to prevent neutral units and buildings from attacking paused players in the post game. 
- These are cleaned up in the reset procedure. All units are resumed and invulnerability is turned off.

### CODE REVIEW

**Comment by Microhive** [comment]
@dtchitt that is of course one option. The problem I am trying to solve though is to stop everything in the game. This includes unit movements (visible movements in the corners and via the minimap), unit training and related noises, attack pings on the map, etc. It goes further than just removing sound.

**Comment by dtchitt** [comment]
Ah okay I thought you were just worried about sounds. Okay Ill need to get someone to help me test to make sure it doesnt lead to any issues in restarts

**Comment by dtchitt** [comment]
Actually I was able to test just now, one problem this causes barracks/ports to be vulnerable on restarts. I would suggest skipping over structures when setting them invulnerable and vulnerable. I believe the unit queue corruption is not going to be an issue with the way you did it. I was not able to produce the bug in my testing. Keep in mind, its been a long time since I dealt with this bug so I may be testing for it wrong. If it comes up we will know its from this.

**Comment by Microhive** [comment]
Ah, I totally forgot about that. I can make a fix for that to tomorrow evening. 

This PR can wait for another patch release, since it is a purely UX improvement.

But if you want this in now, you can adjust it yourself, by filtering away buildings in the unpausing all units function.

**Comment by dtchitt** [comment]
I might do it tonight if I have time to sit down and work on, I gotta do the unit count tracking still as well

**Comment by Microhive** [comment]
Alright, I added a filter to ensuring only non-buildings are made vulnerable again. 

I also rearranged the resume functionality to occur later in the process.

**Pull request merged**
